name: Publish package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          python -m pip install -U pip poetry
          poetry config virtualenvs.create false
        shell: bash
      - name: Install dependencies
        run: poetry install
      - name: Build package
        run: |
          poetry version ${{ env.RELEASE_TAG }}
          poetry build
        shell: bash
      # From https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
